server:
  port: ${PORT:0}

spring:
  profiles: default
  application:
    name: servicio-productos

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka